Config = {}

---SEEDS for inventory 2.0
 --[[
 ["aloeseed"] =
 {
     label = "Aloe Vera mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["agaveseed"] =
 {
     label = "Agávé mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["wintergreenseed"] =
 {
     label = "Kúszó fajdbogyó mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["huckleberryseed"] =
 {
     label = "Áfonyabokor mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["burdockseed"] =
 {
     label = "Bojtorján mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["bulrushseed"] =
 {
     label = "Nád mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["blackcurrantseed"] =
 {
     label = "Fekete Ribiszke mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["alaskanginseed"] =
 {
     label = "Alaszkai Ginzeng mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["yarrowseed"] =
 {
     label = "Vörös Cickafark mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["wildmintseed"] =
 {
     label = "Vad Menta mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["viosnwdrpseed"] =
 {
     label = "Kikeleti Hóvirág mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["thymeseed"] =
 {
     label = "Kakukkfű mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["redsageseed"] =
 {
     label = "Vörösgyökerű zsálya mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["prariepoppyseed"] =
 {
     label = "Vadmák mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["orleanderseed"] =
 {
     label = "Leander mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["oreganoseed"] =
 {
     label = "Oregánó mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["texasbonseed"] =
 {
     label = "Kék Csillagfürt mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["wisteriaseed"] =
 {
     label = "Lilaakác mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["agaritaseed"] =
 {
     label = "Agarita mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["wrhubarbseed"] =
 {
     label = "Vad Rebarbara mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["chocdaisyseed"] =
 {
     label = "Csokoládé Virág mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["cardinalflowerseed"] =
 {
     label = "Tűzpiros Lobélia mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["bloodflowerseed"] =
 {
     label = "Selyembokor mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["bitterweedseed"] =
 {
     label = "Sárga Őzsirózsa mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["milkweedseed"] =
 {
     label = "Selyemkóró mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["indtobaccoseed"] =
 {
     label = "Indián Dohány mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["humbirdsageseed"] =
 {
     label = "Hummingbird Zsálya mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["goldencurrantseed"] =
 {
     label = "Arany ribiszke mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["feverfewseed"] =
 {
     label = "Őszi margitvirág mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["engmaceseed"] =
 {
     label = "Cickafark mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["desertsageseed"] =
 {
     label = "Sivatagi Zsálya mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["garlicseed"] =
 {
     label = "Fokhagyma mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["tobaccoseed"] =
 {
     label = "Dohánymag",
     description = "Virginia dohány, Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["potatoseed"] =
 {
     label = "Burgonya mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["btobaccoseed"] =
 {
     label = "Dohánymag",
     description = "Burnley dohány, Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["wheatseed"] =
 {
     label = "Búza mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["carrotseed"] =
 {
     label = "Répa mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["carrot3seed"] =
 {
     label = "Kis répa mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["lettuceseed"] =
 {
     label = "Saláta mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["ginsengseed"] =
 {
     label = "Ginseng mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["berryseed"] =
 {
     label = "Málna mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["bberryseed"] =
 {
     label = "Szeder mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["artichokeseed"] =
 {
     label = "Articsóka mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["cottonseed"] =
 {
     label = "Gyapot mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["sugarcaneseed"] =
 {
     label = "Cukornád mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["cornseed"] =
 {
     label = "Kukorica mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["broccoliseed"] =
 {
     label = "Brokkoli mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["tomatoseed"] =
 {
     label = "Paradicsom mag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ["seedlingseed"] =
 {
     label = "Növénymag",
     description = "Vetőmag",
     weight = 0.001,
     canBeDropped = true,
     canBeUsed = true,
     requireLvl = 0,
     limit = 50,
     imgsrc = "items/seed.png",
     type = "item_standard",
 },
 ]]
 --HARVESTED ITEMS for inventory 2.0
 --[[
	["wheat"] =
    {
        label = "Búza",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/wheat.png",
        type = "item_standard",

    },
	["hay"] =
    {
        label = "Szalma",
        description = "Termék, abrak",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/hay.png",
        type = "item_standard",


    },
	["apple"] =
    {
        label = "Alma",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/apple.png",
        type = "item_standard",


    },
    ["barack"] =
    {
        label = "Barack",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/barack.png",
        type = "item_standard",
    },
    ["artichoke"] =
    {
        label = "Articsóka",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/artichoke.png",
        type = "item_standard",
    },
    ["broccoli"] =
    {
        label = "Brokkoli",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/broccoli.png",
        type = "item_standard",
    },
    ["carrot"] =
    {
        label = "Répa",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/carrot.png",
        type = "item_standard",
    },
    ["corn"] =
    {
        label = "Kukorica",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/corn.png",
        type = "item_standard",
    },
    ["cotton"] =
    {
        label = "Gyapot",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/cotton.png",
        type = "item_standard",
    },
    ["btobacco"] =
    {
        label = "Burnley dohánylevél",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/btobacco.png",
        type = "item_standard",
    },
    ["tobacco"] =
    {
        label = "Dohánylevél",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/tobacco.png",
        type = "item_standard",
    },
    ["tomato"] =
    {
        label = "Paradicsom",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/tomato.png",
        type = "item_standard",
    },
    ["potato"] =
    {
        label = "Burgonya",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/potato.png",
        type = "item_standard",
    },
    ["seedling"] =
    {
        label = "Növény",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/seed.png",
        type = "item_standard",
    },
    ["lettuce"] =
    {
        label = "Saláta",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/lettuce.png",
        type = "item_standard",
    },
    ["ginseng"] =
    {
        label = "Ginzeng",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/ginseng.png",
        type = "item_standard",
    },
    ["berry"] =
    {
        label = "Málna",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/berry.png",
        type = "item_standard",
    },
    ["bberry"] =
    {
        label = "Szeder",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/bberry.png",
        type = "item_standard",
    },
    ["sugar"] =
    {
        label = "Cukor",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = true,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/sugar.png",
        type = "item_standard",
    },
    ["garlic"] =
    {
        label = "Fokhagyma",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/garlic.png",
        type = "item_standard",
    },
    ["desertsage"] =
    {
        label = "Sivatagi Zsálya",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/desertsage.png",
        type = "item_standard",
    },
    ["engmace"] =
    {
        label = "Cickafark",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/engmace.png",
        type = "item_standard",
    },
    ["feverfew"] =
    {
        label = "Őszi margitvirág",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/feverfew.png",
        type = "item_standard",
    },
    ["goldencurrant"] =
    {
        label = "Arany ribiszke",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/goldencurrant.png",
        type = "item_standard",
    },
    ["humbirdsage"] =
    {
        label = "Hummingbird Zsálya",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/humbirdsage.png",
        type = "item_standard",
    },
    ["indtobacco"] =
    {
        label = "Indián Dohány",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/indtobacco.png",
        type = "item_standard",
    },
    ["milkweed"] =
    {
        label = "Selyemkóró",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/milkweed.png",
        type = "item_standard",
    },
    ["bitterweed"] =
    {
        label = "Sárga Őzsirózsa",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/bitterweed.png",
        type = "item_standard",
    },
    ["bloodflower"] =
    {
        label = "Selyembokor",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/bloodflower.png",
        type = "item_standard",
    },
    ["cardinalflower"] =
    {
        label = "Tűzpiros Lobélia",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/cardinalflower.png",
        type = "item_standard",
    },
    ["chocdaisy"] =
    {
        label = "Csokoládé virág",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/chocdaisy.png",
        type = "item_standard",
    },
    ["wrhubarb"] =
    {
        label = "Vad Rebarbara",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/wrhubarb.png",
        type = "item_standard",
    },
    ["agarita"] =
    {
        label = "Agarita",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/agarita.png",
        type = "item_standard",
    },
    ["wisteria"] =
    {
        label = "Lilaakác",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/wisteria.png",
        type = "item_standard",
    },
    ["texasbon"] =
    {
        label = "Kék Csillagfürt",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/texasbon.png",
        type = "item_standard",
    },
    ["oregano"] =
    {
        label = "Oregánó",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/oregano.png",
        type = "item_standard",
    },
    ["orleander"] =
    {
        label = "Leander",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/orleander.png",
        type = "item_standard",
    },
    ["prariepoppy"] =
    {
        label = "Vadmák",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/prariepoppy.png",
        type = "item_standard",
    },
    ["redsage"] =
    {
        label = "Vörösgyökerű zsálya",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/redsage.png",
        type = "item_standard",
    },
    ["thyme"] =
    {
        label = "Kakukkfű",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/thyme.png",
        type = "item_standard",
    },
    ["viosnwdrp"] =
    {
        label = "Kikeleti Hóvirág",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/viosnwdrp.png",
        type = "item_standard",
    },
    ["wildmint"] =
    {
        label = "Vad Menta",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/wildmint.png",
        type = "item_standard",
    },
    ["yarrow"] =
    {
        label = "Vörös Cickafark",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/yarrow.png",
        type = "item_standard",
    },
    ["alaskangin"] =
    {
        label = "Alaszkai Ginzeng",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/alaskangin.png",
        type = "item_standard",
    },
    ["blackcurrant"] =
    {
        label = "Fekete Ribiszke",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/blackcurrant.png",
        type = "item_standard",
    },
    ["bulrush"] =
    {
        label = "Nádszál",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/bulrush.png",
        type = "item_standard",
    },
    ["burdock"] =
    {
        label = "Bojtorján",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/burdock.png",
        type = "item_standard",
    },
    ["huckleberry"] =
    {
        label = "Áfonya",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/huckleberry.png",
        type = "item_standard",
    },
    ["wintergreen"] =
    {
        label = "Kúszó fajdbogyó",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/wintergreen.png",
        type = "item_standard",
    },
    ["agave"] =
    {
        label = "Agávé",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/agave.png",
        type = "item_standard",
    },
    ["aloe"] =
    {
        label = "Aloe Vera",
        description = "Termék, alapanyag",
        weight = 0.01,
        canBeDropped = true,
        canBeUsed = false,
        requireLvl = 0,
        limit = 100,
        imgsrc = "items/aloe.png",
        type = "item_standard",
    },

 ]]
